title = "Osprey Example Site"
baseURL = "https://iani.github.io/sudel"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "Mainroad"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "iani"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

publishdir = "docs"


[Author]
    name = "Iannis Zannos"
    bio = "Computer Music and Interactive Media Arts"
    avatar = "img/avatar.png"


[Params]
    subtitle = "Sudelbüchlein" # Subtitle of your site
    description = "Iannis Zannos Personal blog about everything" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["post"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

